name: build

on:
  workflow_dispatch: 

jobs:
  ios-build:
    runs-on: macos-12
    env:
      XC_VERSION: ${{ '13.4.1' }}
      XC_WORKSPACE: ${{ 'WindowsAzureMessaging.xcworkspace' }}
      XC_SCHEME: ${{ 'WindowsAzureMessaging iOS Framework' }}
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true

    - name: Select Xcode
      run: "sudo xcode-select -switch /Applications/Xcode_$XC_VERSION.app"

    - name: iOS Analyze
      run: /usr/bin/xcodebuild analyze -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'

    - name: iOS Build
      run: /usr/bin/xcodebuild build -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS'
    
    - name: Upload iOS Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: ~/Library/Developer/Xcode/DerivedData

  tvos-build:
    runs-on: macos-12
    env:
      XC_VERSION: ${{ '13.4.1' }}
      XC_WORKSPACE: ${{ 'WindowsAzureMessaging.xcworkspace' }}
      XC_SCHEME: ${{ 'WindowsAzureMessaging tvOS Framework' }}
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true

    - name: Select Xcode
      run: "sudo xcode-select -switch /Applications/Xcode_$XC_VERSION.app"

    - name: iOS Analyze
      run: /usr/bin/xcodebuild analyze -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=tvOS Simulator,name=Apple TV 4K (2nd generation)'

    - name: iOS Test
      run: /usr/bin/xcodebuild build -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=tvOS Simulator,name=Apple TV 4K (2nd generation)'

    - name: Upload tvOS Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tvos-build
        path: ~/Library/Developer/Xcode/DerivedData

  macos-build:
    runs-on: macos-12
    env:
      XC_VERSION: ${{ '13.4.1' }}
      XC_WORKSPACE: ${{ 'WindowsAzureMessaging.xcworkspace' }}
      XC_SCHEME: ${{ 'WindowsAzureMessaging macOS Framework' }}
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true

    - name: Select Xcode
      run: "sudo xcode-select -switch /Applications/Xcode_$XC_VERSION.app"

    - name: macOS Analyze
      run: /usr/bin/xcodebuild analyze -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=macOS'

    - name: macOS Build
      run: /usr/bin/xcodebuild build -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=macOS'
  
    - name: Upload macOS Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: ~/Library/Developer/Xcode/DerivedData
    
  mac-catalyst-build:
    runs-on: macos-12
    env:
      XC_VERSION: ${{ '13.4.1' }}
      XC_WORKSPACE: ${{ 'WindowsAzureMessaging.xcworkspace' }}
      XC_SCHEME: ${{ 'WindowsAzureMessaging iOS Framework' }}
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true

    - name: Select Xcode
      run: "sudo xcode-select -switch /Applications/Xcode_$XC_VERSION.app"

    - name: macOS Analyze
      run: /usr/bin/xcodebuild analyze -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=macOS'

    - name: macOS Build
      run: /usr/bin/xcodebuild build -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=macOS'

    - name: Upload macOS Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mac-catalyst-build
        path: ~/Library/Developer/Xcode/DerivedData